/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

#define DEFAULT_LOCAL_PORT_RANGE_FIRST 27183

#define DEFAULT_LOCAL_PORT_RANGE_LAST 27199

//#define HAVE_ASPRINTF

#undef HAVE_SOCK_CLOEXEC

#define HAVE__strdup

#define HAVE_USB

#undef HAVE_V4L2

//#define HAVE_VASPRINTF

#define PORTABLE

#define PREFIX "/usr/local"

#define SCRCPY_VERSION "2.4"

#undef SERVER_DEBUGGER

#define SERVER_DEBUGGER_METHOD_NEW

#define WINVER 0x0600

#define _GNU_SOURCE

#define _POSIX_C_SOURCE 200809L

#define _WIN32_WINNT 0x0600

#define _XOPEN_SOURCE 700

